# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90a9e425c81a4029dc2a5b9bfa5db7dc157b8567a5709aa0492cbc4f47f51ae9141c997b096fde70a60f04b3381ecaef04795a0946898103fb1f434f3f76abba

test:
  secret_key_base: daa37f0b49dd1ffc46f4aff32292c57de680ef4f2ee8ead1e194f298482502a5da1e21aa10eac824597bd67a5f33229828a5a6dd509e2d7007b3c162d7aff119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
